### ISSUE TITLE
我是中国用户

### ISSUE THREAD

**Issue by sunshangfeng** [jlmd/UpcomingMoviesMVP#2]
我无法导入到 android 工作室

Gradle version 1.10 is required. Current version is 2.2.1. If using the gradle wrapper, try editing the distributionUrl in D:\AndroidStudioProjects\UpcomingMoviesMVP\gradle\wrapper\gradle-wrapper.properties to gradle-1.10-all.zip.

Please fix the project's Gradle settings.

Consult IDE log for more details (Help | Show Log)

**Comment by jlmd** [comment]
Sorry, for the issue, it's solved in last commit.
